title: Zhongshuo Zhao's Homepage
page-top-title: Zhongshuo Zhao
top-section-bg-text: Automation
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Zhongshuo Zhao 2026-2029. All Rights Reserved.'
github-link:
  text: Github
  href: https://github.com/jz2306836076-sys
license-link:
  text: License
  href: https://github.com/jz2306836076-sys/jz2306836076-sys.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Zhongshuo Zhao&ensp;|&ensp;赵中硕
    href: '#page-top' # Default to '#<id>' if not specified
